# Generated by Django 4.1.2 on 2022-10-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_album', to='music.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_album', to='music.album')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='music.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_album', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='music.artist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_user', to='music.user'),
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='music.song'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_song', to='music.song'),
        ),
    ]
